### ISSUE TITLE
MaxListenersExceededWarning: Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by onemen** [epicweb-dev/kcdshop#34]
`$exerciseNumber_.$stepNumber.$type.tsx` loader repeatedly call `isPortAvailable` 

I've just added a log to `isPortAvailable`. 

this is the output:

```
[dev:server] 🐨  Let's get learning!
[dev:server] Local:            http://localhost:5639
[dev:server] On Your Network:  http://10.100.102.21:5639
[dev:server] Press Ctrl+C to stop
[dev:remix ] Watching Remix app in development mode...
[dev:decs  ]
[dev:decs  ] 18:33:34 - Starting compilation in watch mode...
[dev:decs  ]
[dev:decs  ]
[dev:decs  ] 18:33:34 - Found 0 errors. Watching for file changes.
[dev:remix ] mdx-bundler is possibly an ESM only package and should be bundled with "serverDependenciesToBundle" in remix.config.js.
[dev:remix ] 💿 Built in 2.2s
[dev:server] server.listen - port: 4000 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[dev:server] server.listen - port: 6001 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[dev:server] server.listen - port: 7001 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[dev:server] GET /01/01/problem?_data=routes%2F_app%2B%2F_exercises%2B%2F%24exerciseNumber_.%24stepNumber.%24type 200 - - 1011.006 ms
[dev:server] server.listen - port: 4000 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[dev:server] server.listen - port: 6001 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[dev:server] server.listen - port: 7001 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[dev:server] GET /01/01/solution?_data=routes%2F_app%2B%2F_exercises%2B%2F%24exerciseNumber_.%24stepNumber.%24type 200 - - 89.584 ms
[dev:server] GET /01/02/problem?_data=routes%2F_app%2B%2F_exercises%2B%2F%24exerciseNumber_.%24stepNumber 200 - - 148.646 ms
[dev:server] server.listen - port: 4000 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[dev:server] server.listen - port: 6002 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[dev:server] server.listen - port: 7002 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[dev:server] GET /01/02/problem?_data=routes%2F_app%2B%2F_exercises%2B%2F%24exerciseNumber_.%24stepNumber.%24type 200 - - 100.828 ms
[dev:server] server.listen - port: 4000 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[dev:server] server.listen - port: 6002 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[dev:server] server.listen - port: 7002 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[dev:server] (node:12368) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added to [process]. Use emitter.setMaxListeners() to increase limit
[dev:server] (Use `node --trace-warnings ...` to show where the warning was created)
[dev:server] (node:12368) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGTERM listeners added to [process]. Use emitter.setMaxListeners() to increase limit
[dev:server] GET /01/02/problem?_data=routes%2F_app%2B%2F_exercises%2B%2F%24exerciseNumber_.%24stepNumber.%24type 200 - - 74.748 ms
[dev:server] (node:12368) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 uncaughtException listeners added to [process]. Use emitter.setMaxListeners() to increase limit
[dev:server] server.listen - port: 4000 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[dev:server] server.listen - port: 6001 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[dev:server] server.listen - port: 7001 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[dev:server] GET /01/01/problem?_data=routes%2F_app%2B%2F_exercises%2B%2F%24exerciseNumber_.%24stepNumber.%24type 200 - - 75.447 ms
```

**Comment by onemen** [comment]
Maybe it is from getDiffFiles?

```
[dev:server] (node:15052) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added to [process]. Use emitter.setMaxListeners() to increase limit
[dev:server] (Use `node --trace-warnings ...` to show where the warning was created)
[dev:server] ++++++ MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added to [process]. Use emitter.setMaxListeners() to increase limit
[dev:server]     at __node_internal_genericNodeError (node:internal/errors:867:15)
[dev:server]     at _addListener (node:events:587:17)
[dev:server]     at process.addListener (node:events:605:10)
[dev:server]     at C:\projects\kcd-apps\kcdshop\node_modules\signal-exit\index.js:2:2506
[dev:server]     at Array.filter (<anonymous>)
[dev:server]     at load (C:\projects\kcd-apps\kcdshop\node_modules\signal-exit\index.js:2:2473)
[dev:server]     at module.exports (C:\projects\kcd-apps\kcdshop\node_modules\signal-exit\index.js:2:1194)
[dev:server]     at setExitHandler (file:///C:/projects/kcd-apps/kcdshop/packages/workshop-app/node_modules/execa/lib/kill.js:95:28)
[dev:server]     at execa (file:///C:/projects/kcd-apps/kcdshop/packages/workshop-app/node_modules/execa/index.js:110:22)
[dev:server]     at getDiffFiles (C:\projects\kcd-apps\kcdshop\packages\workshop-app\utils\cache.server.ts:45:32)
```

**Comment by onemen** [comment]
`compileReadme` run many times without caching.
when starting `npm run dev` before starting the app in the browser it runs for all README files.
later when i navigate to next step in an exercise it run again but only for all README in the README exercises root
```
01.nested-routing
02.styling
03.react-components
```
also `getDiffFiles` run for the same input multiple times, without caching

**Comment by onemen** [comment]
I get the above log by adding this code to `server/index.ts`

```js
process.on('warning', error => {
  console.log('+ + + + + + +', error.message, '\n', error.stack)
})
```

After more digging, `compileReadme` using `example/node_modules/.cache/compile-mdx` so that is not the issue.

 [Node's docs](https://nodejs.org/api/events.html#emittersetmaxlistenersn) `By default EventEmitters will print a warning if more than 10 listeners are added for a particular event`

`execa` using [signal-exit](https://github.com/tapjs/signal-exit) under the hood,  signal-exit supposed to allow infinite emitters, so I am not sure why it appears that the warning triggered by `execa`.

Since kcdshop can triggers more than 10 child process at a time this is most likly not a memory leak.

**Comment by onemen** [comment]
killing `execa` processes in not enoght, this is the list of processes running in Windows 11 just by running `npm run build` in powershell terminal


![processes](https://user-images.githubusercontent.com/3650909/231760673-d7ca6113-0b4e-43ad-b6f4-1ea11fabd79d.png)

its **29** , before starting the browser.

**Comment by onemen** [comment]
I will try to post later today each process activated command

**Comment by onemen** [comment]
@kentcdodds

This is the full list.
you can find the tree of processes by looking at process parent process ids

[kcdshop process log](https://github.com/epicweb-dev/kcdshop/files/11225785/kcdshop_process.log)

**Comment by onemen** [comment]
After more investigation I have found that the main reason for `MaxListenersExceededWarning` is multiple calls to 
[`closeWithGrace`](https://github.com/mcollina/close-with-grace/blob/main/index.js#L8-L17)
```js
function closeWithGrace (opts, fn) {
  if (typeof opts === 'function') {
    fn = opts
    opts = {}
  }
  const delay = opts.delay ? opts.delay : 10000
  process.once('SIGTERM', onSignal)
  process.once('SIGINT', onSignal)
  process.once('uncaughtException', onError)
  process.once('unhandledRejection', onError)
```
From the code block above, you can see that closeWithGrace add four new listeners. 
Kcdshop calls closeWithGrace four times:

- getDevProcessesMap - app/utils/process-manager.server.ts
- getTestProcessesMap - app/utils/process-manager.server.ts
- start - server/index.ts
- utils/change-tracker.ts

### development
In development each time `compileMdx` loads cached README.MDX file from `example/node_modules/.cache/compile-mdx` it triggers `app/entry.server.tsx` to call `init` from `utils/apps.server.ts`.</br>init in turn call `getWatcher` (`utils/change-tracker.ts`).
But unexpectedly, (at least to me), each time init call `getWatcher` it creates new watcher and call closeWithGrace again.</br>
That is why listeners number reaching to the moon.

https://github.com/epicweb-dev/kcdshop/blob/9a08f770a365c065d2db50019e8a44dcfeac4682/packages/workshop-app/utils/compile-mdx.server.ts#L88-L93

Reference to line `utils/compile-mdx.server.ts:111` in the output log comes from the file in the build folder `build/utils/utils/compile-mdx.server.ts`,  and it is corresponding to line 90 in the source code.

<details><summary><b>See console log output from closeWithGrace in development</b></summary>

```
> dev
> npm -w example run start


> start
> kcdshop start


> @kentcdodds/workshop-app@0.0.0-semantically-released dev
> cross-env NODE_ENV=development FORCE_COLOR=true run-p --print-label --print-name dev:*

[dev:remix ]
[dev:remix ] > @kentcdodds/workshop-app@0.0.0-semantically-released dev:remix C:\projects\kcd-apps\kcdshop\packages\workshop-app\package.json
[dev:remix ] > remix watch
[dev:remix ]
[dev:server]
[dev:server] > @kentcdodds/workshop-app@0.0.0-semantically-released dev:server C:\projects\kcd-apps\kcdshop\packages\workshop-app\package.json
[dev:server] > tsx watch --clear-screen=false --ignore "app/**" --ignore "build/**" --ignore "node_modules/**" ./start.js
[dev:server]
[dev:utils ]
[dev:utils ] > @kentcdodds/workshop-app@0.0.0-semantically-released dev:utils C:\projects\kcd-apps\kcdshop\packages\workshop-app\package.json
[dev:utils ] > tsx --watch --no-warnings --watch-preserve-output --watch-path ./utils ./other/build-dir.ts utils
[dev:utils ]
[dev:decs  ]
[dev:decs  ] > @kentcdodds/workshop-app@0.0.0-semantically-released dev:decs C:\projects\kcd-apps\kcdshop\packages\workshop-app\package.json
[dev:decs  ] > npm run build:decs --silent -- --preserveWatchOutput --watch
[dev:decs  ]
[dev:remix ]
[dev:remix ] > @kentcdodds/workshop-app@0.0.0-semantically-released dev:remix
[dev:remix ] > remix watch
[dev:remix ]
[dev:server]
[dev:server] > @kentcdodds/workshop-app@0.0.0-semantically-released dev:server
[dev:server] > tsx watch --clear-screen=false --ignore "app/**" --ignore "build/**" --ignore "node_modules/**" ./start.js
[dev:server]
[dev:utils ]
[dev:utils ] > @kentcdodds/workshop-app@0.0.0-semantically-released dev:utils
[dev:utils ] > tsx --watch --no-warnings --watch-preserve-output --watch-path ./utils ./other/build-dir.ts utils
[dev:utils ]
[dev:decs  ]
[dev:decs  ] > @kentcdodds/workshop-app@0.0.0-semantically-released dev:decs
[dev:decs  ] > npm run build:decs --silent -- --preserveWatchOutput --watch
[dev:decs  ]
[dev:server] Debugger listening on ws://127.0.0.1:9229/95710185-082e-4e82-b0b8-e35a288b7803
[dev:server] For help, see: https://nodejs.org/en/docs/inspector
[dev:utils ] Completed running './other/build-dir.ts utils'
[dev:server]
[dev:server] pid(17124) closeWithGrace, totalListeners (6):
[dev:server] Trace:
[dev:server]     at closeWithGrace (node_modules/close-with-grace/index.js:2:764)
[dev:server]     at utils/change-tracker.ts:3:468
[dev:server]     at Object.<anonymous> (utils/change-tracker.ts:4:3)
[dev:server] ----------------------
[dev:server] pid(17124) create new watcher
[dev:server] Trace:
[dev:server]     at getWatcher (utils/change-tracker.ts:2:1454)
[dev:server]     at start (server/index.ts:6:112)
[dev:server]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[dev:server]
[dev:server] pid(17124) closeWithGrace, totalListeners (9):
[dev:server] Trace:
[dev:server]     at closeWithGrace (node_modules/close-with-grace/index.js:2:764)
[dev:server]     at start (server/index.ts:6:693)
[dev:server]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[dev:server] ??  Let's get learning!
[dev:server] Local:            http://localhost:5639
[dev:server] On Your Network:  http://10.100.102.21:5639
[dev:server] Press Ctrl+C to stop
[dev:remix ] Watching Remix app in development mode...
[dev:decs  ]
[dev:decs  ] 11:40:33 - Starting compilation in watch mode...
[dev:decs  ]
[dev:remix ] mdx-bundler is possibly an ESM only package and should be bundled with "serverDependenciesToBundle" in remix.config.js.
[dev:remix ] ?? Built in 2.5s
[dev:decs  ]
[dev:decs  ] 11:40:36 - Found 0 errors. Watching for file changes.
[dev:server]
[dev:server] pid(17124) closeWithGrace, totalListeners (13):
[dev:server] Trace:
[dev:server]     at closeWithGrace (node_modules/close-with-grace/index.js:2:764)
[dev:server]     at build/remix.js:5:466
[dev:server]     at Object.<anonymous> (utils/compile-mdx.server.ts:111:26)
[dev:server] ----------------------
[dev:server] pid(17124) create new watcher
[dev:server] Trace:
[dev:server]     at getWatcher (build/remix.js:2:12332)
[dev:server]     at init (build/remix.js:5:2330)
[dev:server]     at build/remix.js:5:22153
[dev:server]     at Object.<anonymous> (utils/compile-mdx.server.ts:111:26)
[dev:server]
[dev:server] pid(17124) closeWithGrace, totalListeners (17):
[dev:server] Trace:
[dev:server]     at closeWithGrace (node_modules/close-with-grace/index.js:2:764)
[dev:server]     at getDevProcessesMap (utils/cache.server.ts:88:65)
[dev:server]     at utils/cache.server.ts:88:65
[dev:server]
[dev:server] pid(17124) closeWithGrace, totalListeners (21):
[dev:server] Trace:
[dev:server]     at closeWithGrace (node_modules/close-with-grace/index.js:2:764)
[dev:server]     at getTestProcessesMap (utils/cache.server.ts:88:65)
[dev:server]     at utils/cache.server.ts:88:65
[dev:server] GET / 200 - - 1074.363 ms
[dev:server]
[dev:server] pid(17124) closeWithGrace, totalListeners (25):
[dev:server] Trace:
[dev:server]     at closeWithGrace (node_modules/close-with-grace/index.js:2:764)
[dev:server]     at build/remix.js:5:466
[dev:server]     at Object.<anonymous> (utils/compile-mdx.server.ts:111:26)
[dev:server] ----------------------
[dev:server] pid(17124) create new watcher
[dev:server] Trace:
[dev:server]     at getWatcher (build/remix.js:2:12332)
[dev:server]     at init (build/remix.js:5:2330)
[dev:server]     at build/remix.js:5:22153
[dev:server]     at Object.<anonymous> (utils/compile-mdx.server.ts:111:26)
[dev:server]
[dev:server] pid(17124) closeWithGrace, totalListeners (29):
[dev:server] Trace:
[dev:server]     at closeWithGrace (node_modules/close-with-grace/index.js:2:764)
[dev:server]     at build/remix.js:5:466
[dev:server]     at Object.<anonymous> (utils/compile-mdx.server.ts:111:26)
[dev:server] ----------------------
[dev:server] pid(17124) create new watcher
[dev:server] Trace:
[dev:server]     at getWatcher (build/remix.js:2:12332)
[dev:server]     at init (build/remix.js:5:2330)
[dev:server]     at build/remix.js:5:22153
[dev:server]     at Object.<anonymous> (utils/compile-mdx.server.ts:111:26)
[dev:server] GET /01?_data=routes%2F_app%2B%2F_exercises%2B%2F_layout 200 - - 148.499 ms
[dev:server] GET /01?_data=routes%2F_app%2B%2F_exercises%2B%2F%24exerciseNumber 200 - - 97.240 ms
[dev:server]
[dev:server] pid(17124) closeWithGrace, totalListeners (33):
[dev:server] Trace:
[dev:server]     at closeWithGrace (node_modules/close-with-grace/index.js:2:764)
[dev:server]     at build/remix.js:5:466
[dev:server]     at Object.<anonymous> (utils/compile-mdx.server.ts:111:26)
[dev:server] ----------------------
[dev:server] pid(17124) create new watcher
[dev:server] Trace:
[dev:server]     at getWatcher (build/remix.js:2:12332)
[dev:server]     at init (build/remix.js:5:2330)
[dev:server]     at build/remix.js:5:22153
[dev:server]     at Object.<anonymous> (utils/compile-mdx.server.ts:111:26)
[dev:server]
[dev:server] pid(17124) closeWithGrace, totalListeners (37):
[dev:server] Trace:
[dev:server]     at closeWithGrace (node_modules/close-with-grace/index.js:2:764)
[dev:server]     at build/remix.js:5:466
[dev:server]     at Object.<anonymous> (utils/compile-mdx.server.ts:111:26)
[dev:server] ----------------------
[dev:server] pid(17124) create new watcher
[dev:server] Trace:
[dev:server]     at getWatcher (build/remix.js:2:12332)
[dev:server]     at init (build/remix.js:5:2330)
[dev:server]     at build/remix.js:5:22153
[dev:server]     at Object.<anonymous> (utils/compile-mdx.server.ts:111:26)
[dev:server] getFreshValue for getDiffCodeImpl App 1 playground, App 2 exercises.01.nested-routing.01.solution.outlet
[dev:server] GET /01/01/problem?_data=routes%2F_app%2B%2F_exercises%2B%2F%24exerciseNumber_.%24stepNumber 200 - - 95.233 ms
[dev:server] (node:17124) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added to [process]. Use emitter.setMaxListeners() to increase limit
[dev:server] (Use `node --trace-warnings ...` to show where the warning was created)
[dev:server] (node:17124) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGTERM listeners added to [process]. Use emitter.setMaxListeners() to increase limit
[dev:server] compileMarkdownString getFreshValue for diff
[dev:server] GET /01/01/problem?_data=routes%2F_app%2B%2F_exercises%2B%2F%24exerciseNumber_.%24stepNumber.%24type 200 - - 148.878 ms
[dev:server]
[dev:server] pid(17124) closeWithGrace, totalListeners (41):
[dev:server] Trace:
[dev:server]     at closeWithGrace (node_modules/close-with-grace/index.js:2:764)
[dev:server]     at build/remix.js:5:466
[dev:server]     at Object.<anonymous> (utils/compile-mdx.server.ts:111:26)
[dev:server] ----------------------
[dev:server] pid(17124) create new watcher
[dev:server] Trace:
[dev:server]     at getWatcher (build/remix.js:2:12332)
[dev:server]     at init (build/remix.js:5:2330)
[dev:server]     at build/remix.js:5:22153
[dev:server]     at Object.<anonymous> (utils/compile-mdx.server.ts:111:26)
[dev:server] (node:17124) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 uncaughtException listeners added to [process]. Use emitter.setMaxListeners() to increase limit
[dev:server]
[dev:server] pid(17124) closeWithGrace, totalListeners (45):
[dev:server] Trace:
[dev:server]     at closeWithGrace (node_modules/close-with-grace/index.js:2:764)
[dev:server]     at build/remix.js:5:466
[dev:server]     at Object.<anonymous> (utils/compile-mdx.server.ts:111:26)
[dev:server] ----------------------
[dev:server] pid(17124) create new watcher
[dev:server] Trace:
[dev:server]     at getWatcher (build/remix.js:2:12332)
[dev:server]     at init (build/remix.js:5:2330)
[dev:server]     at build/remix.js:5:22153
[dev:server]     at Object.<anonymous> (utils/compile-mdx.server.ts:111:26)
[dev:server] (node:17124) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 unhandledRejection listeners added to [process]. Use emitter.setMaxListeners() to increase limit
[dev:server]
[dev:server] pid(17124) closeWithGrace, totalListeners (49):
[dev:server] Trace:
[dev:server]     at closeWithGrace (node_modules/close-with-grace/index.js:2:764)
[dev:server]     at build/remix.js:5:466
[dev:server]     at Object.<anonymous> (utils/compile-mdx.server.ts:111:26)
[dev:server] ----------------------
[dev:server] pid(17124) create new watcher
[dev:server] Trace:
[dev:server]     at getWatcher (build/remix.js:2:12332)
[dev:server]     at init (build/remix.js:5:2330)
[dev:server]     at build/remix.js:5:22153
[dev:server]     at Object.<anonymous> (utils/compile-mdx.server.ts:111:26)
[dev:server]
[dev:server] pid(17124) closeWithGrace, totalListeners (53):
[dev:server] Trace:
[dev:server]     at closeWithGrace (node_modules/close-with-grace/index.js:2:764)
[dev:server]     at build/remix.js:5:466
[dev:server]     at Object.<anonymous> (utils/compile-mdx.server.ts:111:26)
[dev:server] ----------------------
[dev:server] pid(17124) create new watcher
[dev:server] Trace:
[dev:server]     at getWatcher (build/remix.js:2:12332)
[dev:server]     at init (build/remix.js:5:2330)
[dev:server]     at build/remix.js:5:22153
[dev:server]     at Object.<anonymous> (utils/compile-mdx.server.ts:111:26)
[dev:server] GET /01/01/problem?preview=diff&_data=root 200 - - 48.320 ms
[dev:server] GET /01/01/problem?preview=diff&_data=routes%2F_app%2B%2F_exercises%2B%2F_layout 200 - - 223.335 ms
[dev:server] GET /01/01/problem?preview=diff&_data=routes%2F_app%2B%2F_exercises%2B%2F%24exerciseNumber_.%24stepNumber 200 - - 124.821 ms
[dev:server] GET /01/01/problem?preview=diff&_data=routes%2F_app%2B%2F_exercises%2B%2F%24exerciseNumber_.%24stepNumber.%24type 200 - - 176.921 ms
[dev:server]
[dev:server] pid(17124) closeWithGrace, totalListeners (57):
[dev:server] Trace:
[dev:server]     at closeWithGrace (node_modules/close-with-grace/index.js:2:764)
[dev:server]     at build/remix.js:5:466
[dev:server]     at Object.<anonymous> (utils/compile-mdx.server.ts:111:26)
[dev:server] ----------------------
[dev:server] pid(17124) create new watcher
[dev:server] Trace:
[dev:server]     at getWatcher (build/remix.js:2:12332)
[dev:server]     at init (build/remix.js:5:2330)
[dev:server]     at build/remix.js:5:22153
[dev:server]     at Object.<anonymous> (utils/compile-mdx.server.ts:111:26)
[dev:server] GET /01?_data=root 200 - - 51.122 ms
[dev:server]
[dev:server] pid(17124) closeWithGrace, totalListeners (61):
[dev:server] Trace:
[dev:server]     at closeWithGrace (node_modules/close-with-grace/index.js:2:764)
[dev:server]     at build/remix.js:5:466
[dev:server]     at Object.<anonymous> (utils/compile-mdx.server.ts:111:26)
[dev:server] ----------------------
[dev:server] pid(17124) create new watcher
[dev:server] Trace:
[dev:server]     at getWatcher (build/remix.js:2:12332)
[dev:server]     at init (build/remix.js:5:2330)
[dev:server]     at build/remix.js:5:22153
[dev:server]     at Object.<anonymous> (utils/compile-mdx.server.ts:111:26)
[dev:server] (node:17124) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 before:purge listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
[dev:server]
[dev:server] pid(17124) closeWithGrace, totalListeners (65):
[dev:server] Trace:
[dev:server]     at closeWithGrace (node_modules/close-with-grace/index.js:2:764)
[dev:server]     at build/remix.js:5:466
[dev:server]     at Object.<anonymous> (utils/compile-mdx.server.ts:111:26)
[dev:server] ----------------------
[dev:server] pid(17124) create new watcher
[dev:server] Trace:
[dev:server]     at getWatcher (build/remix.js:2:12332)
[dev:server]     at init (build/remix.js:5:2330)
[dev:server]     at build/remix.js:5:22153
[dev:server]     at Object.<anonymous> (utils/compile-mdx.server.ts:111:26)
[dev:server]
[dev:server] pid(17124) closeWithGrace, totalListeners (69):
[dev:server] Trace:
[dev:server]     at closeWithGrace (node_modules/close-with-grace/index.js:2:764)
[dev:server]     at build/remix.js:5:466
[dev:server]     at Object.<anonymous> (utils/compile-mdx.server.ts:111:26)
[dev:server] ----------------------
[dev:server] pid(17124) create new watcher
[dev:server] Trace:
[dev:server]     at getWatcher (build/remix.js:2:12332)
[dev:server]     at init (build/remix.js:5:2330)
[dev:server]     at build/remix.js:5:22153
[dev:server]     at Object.<anonymous> (utils/compile-mdx.server.ts:111:26)
[dev:server]
[dev:server] pid(17124) closeWithGrace, totalListeners (73):
[dev:server] Trace:
[dev:server]     at closeWithGrace (node_modules/close-with-grace/index.js:2:764)
[dev:server]     at build/remix.js:5:466
[dev:server]     at Object.<anonymous> (utils/compile-mdx.server.ts:111:26)
[dev:server] ----------------------
[dev:server] pid(17124) create new watcher
[dev:server] Trace:
[dev:server]     at getWatcher (build/remix.js:2:12332)
[dev:server]     at init (build/remix.js:5:2330)
[dev:server]     at build/remix.js:5:22153
[dev:server]     at Object.<anonymous> (utils/compile-mdx.server.ts:111:26)
[dev:server] GET /01/01/solution?_data=root 200 - - 48.293 ms
[dev:server] GET /01/01/solution?_data=routes%2F_app%2B%2F_exercises%2B%2F_layout 200 - - 209.038 ms
[dev:server] GET /01/01/solution?_data=routes%2F_app%2B%2F_exercises%2B%2F%24exerciseNumber_.%24stepNumber 200 - - 157.643 ms
[dev:server] GET /01/01/solution?_data=routes%2F_app%2B%2F_exercises%2B%2F%24exerciseNumber_.%24stepNumber.%24type 200 - - 111.872 ms
[dev:server]
[dev:server] pid(17124) closeWithGrace, totalListeners (77):
[dev:server] Trace:
[dev:server]     at closeWithGrace (node_modules/close-with-grace/index.js:2:764)
[dev:server]     at build/remix.js:5:466
[dev:server]     at Object.<anonymous> (utils/compile-mdx.server.ts:111:26)
[dev:server] ----------------------
[dev:server] pid(17124) create new watcher
[dev:server] Trace:
[dev:server]     at getWatcher (build/remix.js:2:12332)
[dev:server]     at init (build/remix.js:5:2330)
[dev:server]     at build/remix.js:5:22153
[dev:server]     at Object.<anonymous> (utils/compile-mdx.server.ts:111:26)
[dev:server]
[dev:server] pid(17124) closeWithGrace, totalListeners (81):
[dev:server] Trace:
[dev:server]     at closeWithGrace (node_modules/close-with-grace/index.js:2:764)
[dev:server]     at build/remix.js:5:466
[dev:server]     at Object.<anonymous> (utils/compile-mdx.server.ts:111:26)
[dev:server] ----------------------
[dev:server] pid(17124) create new watcher
[dev:server] Trace:
[dev:server]     at getWatcher (build/remix.js:2:12332)
[dev:server]     at init (build/remix.js:5:2330)
[dev:server]     at build/remix.js:5:22153
[dev:server]     at Object.<anonymous> (utils/compile-mdx.server.ts:111:26)
[dev:server] getFreshValue for getDiffCodeImpl App 1 playground, App 2 exercises.01.nested-routing.02.solution.outlet-context
[dev:server] GET /01/02/problem?_data=routes%2F_app%2B%2F_exercises%2B%2F%24exerciseNumber_.%24stepNumber 200 - - 84.170 ms
[dev:server] compileMarkdownString getFreshValue for diff
[dev:server] GET /01/02/problem?_data=routes%2F_app%2B%2F_exercises%2B%2F%24exerciseNumber_.%24stepNumber.%24type 200 - - 152.694 ms
```

</details>

### production
In production, there are only five calls to closeWithGrace and total listeners recorded in closeWithGrace are 20.</br>from `change-tracker.ts` it called twice for some reason. 
<details><summary><b>See console log output from closeWithGrace in production</b></summary>

```
> dev
> kcdshop start


pid(18888) closeWithGrace, totalListeners (4):
Trace:
    at closeWithGrace (node_modules/close-with-grace/index.js:22:17)
    at Object.<anonymous> (build/utils/change-tracker.js:52:37)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)

pid(18888) closeWithGrace, totalListeners (8):
Trace:
    at closeWithGrace (node_modules/close-with-grace/index.js:22:17)
    at Object.<anonymous> (utils/change-tracker.ts:25:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)

pid(18888) closeWithGrace, totalListeners (12):
Trace:
    at closeWithGrace (node_modules/close-with-grace/index.js:22:17)
    at getDevProcessesMap (app/utils/process-manager.server.ts:43:2)
    at Object.<anonymous> (app/utils/process-manager.server.ts:36:30)

pid(18888) closeWithGrace, totalListeners (16):
Trace:
    at closeWithGrace (node_modules/close-with-grace/index.js:22:17)
    at getTestProcessesMap (app/utils/process-manager.server.ts:55:2)
    at Object.<anonymous> (app/utils/process-manager.server.ts:38:31)

pid(18888) closeWithGrace, totalListeners (20):
Trace:
    at closeWithGrace (node_modules/close-with-grace/index.js:22:17)
    at start (build/server/index.js:114:39)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
??  Let's get learning!
Local:            http://localhost:5639
On Your Network:  http://10.100.102.21:5639
Press Ctrl+C to stop
```

</details>
